# Generated by Django 4.1.3 on 2023-01-11 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_team_alter_profile_image"),
    ]

    operations = [
        migrations.DeleteModel(name="Team",),
    ]
