# Generated by Django 4.1.3 on 2023-01-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamName", models.CharField(max_length=30, null=True)),
                ("playerName", models.CharField(max_length=30, null=True)),
                (
                    "playerImage",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
            ],
        ),
    ]
